# Generated by Django 3.2.9 on 2022-06-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
    ]
